# Generated by Django 4.1.1 on 2023-04-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('group', models.CharField(max_length=10)),
                ('prerequisite', models.JSONField()),
                ('horario', models.JSONField()),
                ('note', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'Asignatura',
            },
        ),
    ]
