# Generated by Django 4.1.1 on 2023-04-27 20:16

import Asignatura.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('group', models.CharField(max_length=10)),
                ('prerequisite', models.JSONField(blank=True, default=Asignatura.models.prerequisiteDefault)),
                ('horario', models.JSONField(blank=True, default=Asignatura.models.horarioDefault)),
                ('note', models.CharField(blank=True, default='', max_length=10)),
                ('id_profesor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Asignatura',
            },
        ),
    ]
