# Generated by Django 4.1.1 on 2023-04-28 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Asignatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteAsignatura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_asignatura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Asignatura.asignatura')),
                ('id_estudiante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EstudianteAsignatura',
            },
        ),
    ]
