# Generated by Django 4.1.1 on 2023-04-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignatura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='note',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
