# Generated by Django 4.2 on 2023-04-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asignatura', '0002_rename_note_asignatura_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='grade',
        ),
    ]
