# Generated by Django 4.1.1 on 2023-04-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignatura', '0003_alter_asignatura_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='horario',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='prerequisite',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
