# Generated by Django 4.1.1 on 2023-04-27 01:38

import Asignatura.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignatura', '0004_alter_asignatura_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='horario',
            field=models.JSONField(blank=True, default=Asignatura.models.horarioDefault),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='prerequisite',
            field=models.JSONField(blank=True, default=Asignatura.models.prerequisiteDefault),
        ),
    ]
