# Generated by Django 4.1.1 on 2023-04-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignatura', '0005_alter_asignatura_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
