# Generated by Django 4.2 on 2023-04-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academy_program',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
