# Generated by Django 4.2 on 2023-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('lost_credits', models.CharField(default='0', max_length=10)),
                ('earned_credits', models.CharField(default='0', max_length=10)),
                ('promedio', models.CharField(default='0', max_length=5)),
                ('courses', models.JSONField(blank=True)),
            ],
            options={
                'db_table': 'Tabulado',
            },
        ),
    ]
