# Generated by Django 4.2 on 2023-04-28 18:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tabulado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTabulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateField(default=datetime.date(2023, 4, 28))),
                ('id_tabulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tabulado.tabulado')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserTabulado',
            },
        ),
    ]
