# Generated by Django 4.2 on 2023-04-28 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabulado', '0003_alter_usertabulado_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertabulado',
            name='date_generated',
            field=models.DateField(default=datetime.datetime(2023, 4, 28, 18, 13, 18, 52417, tzinfo=datetime.timezone.utc)),
        ),
    ]
