# Generated by Django 4.2 on 2023-04-28 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabulado', '0004_alter_usertabulado_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertabulado',
            name='date_generated',
            field=models.DateField(default=datetime.datetime(2023, 4, 28, 23, 18, 26, 580135, tzinfo=datetime.timezone.utc)),
        ),
    ]
