# Generated by Django 4.2 on 2023-05-16 22:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('lost_credits', models.CharField(default='0', max_length=10)),
                ('earned_credits', models.CharField(default='0', max_length=10)),
                ('promedio', models.CharField(default='0', max_length=5)),
                ('courses', models.JSONField(blank=True)),
            ],
            options={
                'db_table': 'Tabulado',
            },
        ),
        migrations.CreateModel(
            name='UserTabulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateField(default=datetime.datetime(2023, 5, 16, 22, 24, 18, 37653, tzinfo=datetime.timezone.utc))),
                ('id_tabulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tabulado.tabulado')),
            ],
            options={
                'db_table': 'UserTabulado',
            },
        ),
    ]
