# Generated by Django 4.2 on 2023-05-17 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabulado', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertabulado',
            name='date_generated',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 3, 1, 23, 772993, tzinfo=datetime.timezone.utc)),
        ),
    ]
