# Generated by Django 4.2 on 2023-05-19 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tabulado', '0003_alter_usertabulado_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertabulado',
            name='date_generated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
